# Default values for ibm-automation-foundation-core-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

subscriptions:
  ibmautomation:
    name: ibm-automation
    namespace: gitops-cp-ban-operator
    subscription:
      channel: v1.3
      installPlanApproval: Automatic
      name: ibm-automation
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace
####Namespace needs to be added  